# ruff: noqa: D102, TC001, TC003

from __future__ import annotations

from collections.abc import Coroutine
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol

from bananalecture_backend.schemas.dialogue import DialogueEmotion, DialogueRole, DialogueSpeed


@dataclass(frozen=True, slots=True)
class GeneratedDialogueDraft:
    """Application-level dialogue item generated by an upstream model."""

    role: DialogueRole
    content: str
    emotion: DialogueEmotion
    speed: DialogueSpeed


class ImageGenerator(Protocol):
    """Generate or modify a slide image from a prompt."""

    async def generate_image(self, prompt: str, reference_image: str | None = None) -> bytes: ...


class DialogueGenerator(Protocol):
    """Generate structured dialogues for one slide."""

    async def generate_dialogues(
        self,
        prompt: str,
        image_bytes: bytes | None = None,
    ) -> list[GeneratedDialogueDraft]: ...


class AudioSynthesizer(Protocol):
    """Synthesize one dialogue item into audio bytes."""

    async def generate_audio(self, text: str, role: str, emotion: str, speed: str) -> bytes: ...


class AudioProcessor(Protocol):
    """Concatenate audio assets into a final mp3."""

    async def concatenate_mp3_files(self, inputs: list[Path], output: Path) -> None: ...


class VideoRenderer(Protocol):
    """Render slide clips and concatenate them into a final video."""

    async def render_static_slide_clip(self, image: Path, audio: Path, output: Path) -> None: ...

    async def concatenate_mp4_files(self, inputs: list[Path], output: Path) -> None: ...


class AssetStore(Protocol):
    """Persistent storage for generated assets."""

    async def write_bytes(self, key: str, content: bytes) -> str: ...

    async def read_bytes(self, key: str | None) -> bytes: ...

    async def prepare_output_file(self, key: str) -> Path: ...

    def resolve_file(self, key: str | None) -> Path: ...

    async def create_temp_dir(self, prefix: str) -> Path: ...

    def normalize_key(self, key: str) -> str: ...


class BackgroundTaskRunner(Protocol):
    """Run, cancel, and shutdown application background tasks."""

    def start(self, task_id: str, work: Coroutine[object, object, None]) -> None: ...

    def cancel(self, task_id: str) -> bool: ...

    async def shutdown(self) -> None: ...
